# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Sogedial\OAuthBundle\Entity\User:
            algorithm: sha512
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        api_provider:
            id: sogedial.oauth.user_provider

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ALLOWED_TO_SWITCH]
        ROLE_COMMERCIAL: [ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_ALLOWED_TO_SWITCH, ROLE_ADMIN, ROLE_COMMERCIAL, ROLE_CUSTOMER]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern:    ^/bpi
            fos_oauth:  true
            stateless:  true
            anonymous:  false
            switch_user_stateless: true
            
        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            # Add your favorite authentication process here
            form_login:
                provider: api_provider
                check_path: /oauth/v2/auth_login_check
                login_path: /oauth/v2/auth_login
            logout:
                 path: /oauth/v2/auth_logout
                 target: /oauth/v2/auth_login
            anonymous: true

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        main:
            anonymous: true
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/testapi, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }        
        #- { path: ^/api/users, roles: [ ROLE_SUPER_ADMIN ], methods: POST }
        #- { path: ^/api/products, roles: [ ROLE_ADMIN ], methods: POST }
        #- { path: ^/api/products, roles: [ ROLE_USER ], methods: GET }