<?php

namespace Sogedial\ApiBundle\Repository;

/**
 * GroupAttributRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupAttributRepository extends EntityRepository
{
    protected $alias = 'ga';
}
